--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/MapRender
build-by-default: true
branches:
- master
projects:
  MapRender:
    path: ""
    model: virion
    type: library
...
